In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer 

In [2]:
loc = "data/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/"

dataset = pd.read_csv(loc + 'Data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
X = dataset.iloc[:, :-1].values

In [4]:
y = dataset.iloc[:, 3].values

In [5]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [6]:
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [7]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [9]:
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
X = ct.fit_transform(X)  

In [10]:
labelencoder_y = LabelEncoder()
y = labelencoder_X.fit_transform(y)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

In [12]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[1 1 1 0 1 0 0 1]
[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]
[0 0]


In [13]:
sc_X = StandardScaler()

In [14]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [18]:
X_train.round(3)

array([[-1.   ,  2.646, -0.775,  0.263,  0.124],
       [ 1.   , -0.378, -0.775, -0.254,  0.462],
       [-1.   , -0.378,  1.291, -1.975, -1.531],
       [-1.   , -0.378,  1.291,  0.053, -1.111],
       [ 1.   , -0.378, -0.775,  1.641,  1.72 ],
       [-1.   , -0.378,  1.291, -0.081, -0.168],
       [ 1.   , -0.378, -0.775,  0.952,  0.986],
       [ 1.   , -0.378, -0.775, -0.598, -0.482]])

In [19]:
X_test.round(3)

array([[-1.   ,  2.646, -0.775, -1.459, -0.902],
       [-1.   ,  2.646, -0.775,  1.985,  2.14 ]])